Repository Vizzuality/widget-editor, pull requests merged in 2020-08, with the labels that each got.

#76 Feature/improved state management
  assets/data-flow.png
  src/adapters/rw-adapter/package.json
  src/adapters/rw-adapter/src/index.ts
  src/applications/widget-editor/src/components/color-shemes/component.js
  src/applications/widget-editor/src/components/color-shemes/index.js
  src/applications/widget-editor/src/components/editor-options/component.js
  src/applications/widget-editor/src/components/filter/component.js
  src/applications/widget-editor/src/components/filter/index.js
  src/applications/widget-editor/src/components/map-info/component.js
  src/applications/widget-editor/src/components/query-limit/component.js
  src/applications/widget-editor/src/exposed-hooks/index.js
  src/applications/widget-editor/src/sagas/editor/index.js
  src/applications/widget-editor/src/sagas/widget/getWidgetData.js
  src/applications/widget-editor/src/sagas/widget/index.js
  src/packages/core/src/constants.ts
  src/packages/core/src/services/data.ts
  src/packages/core/src/services/dataset.ts
  src/packages/core/src/services/filters.ts
  src/packages/core/src/services/state-proxy.ts
  src/packages/core/src/services/widget.ts
  src/packages/map/src/index.js
  src/packages/shared/src/modules/editor/actions.js
  src/packages/shared/src/modules/editor/initial-state.js
  src/packages/shared/src/modules/editor/reducers.js
  src/packages/types/src/adapter.ts
  src/packages/types/src/generic.ts
  src/playground/widget-editor/package.json
  src/playground/widget-editor/src/App.js
  src/playground/widget-editor/src/App.scss
  src/playground/widget-editor/src/components/debug-options/index.js
  src/playground/widget-editor/src/components/debug-options/styles.scss
  src/playground/widget-editor/src/components/editor/component.js
  src/playground/widget-editor/src/components/toggle-options/component.js
  src/playground/widget-editor/src/modules/editor-options/initial-state.js
  yarn.lock
Labels: enhancement

#89 Fix an issue where some map widgets crash the editor
  src/adapters/rw-adapter/src/index.ts
  src/applications/widget-editor/src/components/map-info/basemaps.js
  src/applications/widget-editor/src/components/map-info/labels.js
  src/applications/widget-editor/src/sagas/editor/index.js
Labels: 🔥 Hotfix

#93 Fix a bug preventing using the editor in other apps
  src/applications/widget-editor/src/sagas/editor/index.js
Labels: 🔥 Hotfix

#111 Release 2.3.2
  .github/workflows/on_pr.yml
  .release-it.json
  bin/build.sh
  jest.config.js
  package.json
  rollup.config.js
  src/adapters/rw-adapter/src/index.ts
  src/applications/renderer/src/components/chart/component.js
  src/applications/renderer/src/components/chart/styles.js
  src/applications/widget-editor/src/components/editor-options/component.js
  src/applications/widget-editor/src/components/end-user-filters/component.js
  src/applications/widget-editor/src/components/end-user-filters/index.js
  src/applications/widget-editor/src/components/end-user-filters/style.js
  src/applications/widget-editor/src/components/filter/component.js
  src/applications/widget-editor/src/components/filter/index.js
  src/applications/widget-editor/src/components/slice-count/component.js
  src/applications/widget-editor/src/components/slice-count/index.js
  src/applications/widget-editor/src/components/slice-count/style.js
  src/applications/widget-editor/src/sagas/widget/getWidgetData.js
  src/applications/widget-editor/src/sagas/widget/index.js
  src/packages/core/__tests__/state-proxy/helpers.ts
  src/packages/core/__tests__/state-proxy/mock.ts
  src/packages/core/__tests__/state-proxy/state-proxy.test.ts
  src/packages/core/src/charts/bars-grouped-horizontal.ts
  src/packages/core/src/charts/bars-grouped.ts
  src/packages/core/src/charts/bars-horizontal.ts
  src/packages/core/src/charts/bars-stacked-horizontal.ts
  src/packages/core/src/charts/bars-stacked.ts
  src/packages/core/src/charts/bars.ts
  src/packages/core/src/charts/chart-common.ts
  src/packages/core/src/charts/line-multi.ts
  src/packages/core/src/charts/line.ts
  src/packages/core/src/charts/pie.ts
  src/packages/core/src/charts/scatter.ts
  src/packages/core/src/constants.ts
  src/packages/core/src/output-payload/index.ts
  src/packages/core/src/services/data.ts
  src/packages/core/src/services/fields.ts
  src/packages/core/src/services/filters.ts
  src/packages/core/src/services/state-proxy.ts
  src/packages/core/src/services/vega.ts
  src/packages/shared/src/modules/editor/initial-state.js
  src/packages/shared/src/modules/editor/selectors.js
  src/packages/shared/src/modules/end-user-filters/actions.js
  src/packages/shared/src/modules/end-user-filters/index.js
  src/packages/shared/src/modules/end-user-filters/initial-state.js
  src/packages/shared/src/modules/end-user-filters/reducers.js
  src/packages/shared/src/modules/end-user-filters/selectors.js
  src/packages/shared/src/modules/index.js
  src/packages/types/src/adapter.ts
  src/packages/types/src/charts.ts
  src/packages/types/src/filters.ts
  src/packages/types/src/vega.ts
  src/playground/widget-editor/src/components/editor/component.js
  tslint.json
  yarn.lock
Labels: 🏁 Release
